import { useState, useEffect, useCallback } from 'react';
import { adminUsers } from '@/lib/adminUsers';
import { supabase, type Commande, type Menu, type MatierePremiere, type Recette, type CommandeItem, type Category, type Utilisateur } from '@/lib/supabase';
import {
  LayoutDashboard, UtensilsCrossed, Package, ClipboardList, Leaf, Tags, Users, FileBarChart,
  Plus, Edit3, Trash2, X, Search, TrendingUp, DollarSign, ShoppingBag,
  AlertTriangle, Image as ImageIcon, ChevronDown, ChevronRight, ArrowUp, ArrowDown, Printer, Calendar
} from 'lucide-react';

type Tab = 'dashboard' | 'menu' | 'stock' | 'commandes' | 'matiere' | 'categories' | 'utilisateurs' | 'rapports';

export default function Admin() {
  const [tab, setTab] = useState<Tab>('rapports');
  const tabs: { id: Tab; label: string; icon: any }[] = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { id: 'menu', label: 'Menu', icon: UtensilsCrossed },
    { id: 'stock', label: 'Stock', icon: Package },
    { id: 'commandes', label: 'Commandes', icon: ClipboardList },
    { id: 'matiere', label: 'Matière', icon: Leaf },
    { id: 'categories', label: 'Catégories', icon: Tags },
    { id: 'utilisateurs', label: 'Utilisateurs', icon: Users },
    { id: 'rapports', label: 'Rapports', icon: FileBarChart },
  ];
  return (
    <div className="min-h-screen bg-[#0A0A0A] pb-20">
      <div className="sticky top-0 z-30 bg-[#0A0A0A]/95 backdrop-blur border-b border-gray-800">
        <div className="flex items-center gap-1 px-2 py-2 overflow-x-auto">
          {tabs.map((t) => {
            const Icon = t.icon;
            return <button key={t.id} onClick={() => setTab(t.id)} className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap ${tab === t.id? 'bg-[#FF6B00] text-white' : 'text-gray-400 hover:text-white hover:bg-gray-800'}`}><Icon className="w-4 h-4" />{t.label}</button>
          })}
        </div>
      </div>
      <div className="p-4 max-w-6xl mx-auto">
        {tab === 'dashboard' && <DashboardTab />}
        {tab === 'menu' && <MenuTab />}
        {tab === 'stock' && <StockTab />}
        {tab === 'commandes' && <CommandesTab />}
        {tab === 'matiere' && <MatiereTab />}
        {tab === 'categories' && <CategoriesTab />}
        {tab === 'utilisateurs' && <UtilisateursTab />}
        {tab === 'rapports' && <RapportsTab />}
      </div>
    </div>
  );
}

function LoadingSpinner(){ return <div className="flex items-center justify-center py-20"><div className="w-8 h-8 border-2 border-[#FF6B00] border-t-transparent rounded-full animate-spin" /></div>; }
function StatCard({ icon: Icon, label, value, color, bg }: any){ return <div className="bg-[#1A1A1A] rounded-2xl p-4 border border-gray-800"><div className={`w-10 h-10 rounded-xl ${bg} flex items-center justify-center mb-3`}><Icon className={`w-5 h-5 ${color}`} /></div><div className="text-white text-xl font-bold">{value}</div><div className="text-gray-500 text-xs mt-0.5">{label}</div></div>; }
function StatusBadge({ statut }: { statut: string }){ const map:any={ en_attente:{label:'En attente',cls:'bg-gray-700 text-gray-300'}, en_preparation:{label:'En préparation',cls:'bg-blue-900 text-blue-300'}, pret:{label:'Prêt',cls:'bg-green-900 text-green-300'}, paye:{label:'Payé',cls:'bg-green-700 text-white'}}; const s=map[statut]||map.en_attente; return <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${s.cls}`}>{s.label}</span>; }

function DashboardTab(){
  const [commandes,setCommandes]=useState<any[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ const load=async()=>{ const today=new Date().toISOString().split('T')[0]; const {data}=await supabase.from('commandes').select('*').gte('paye_at',today+'T00:00:00').order('paye_at',{ascending:false}); setCommandes(data||[]); setLoading(false); }; load(); },[]);
  if(loading) return <LoadingSpinner/>;
  const totalEncaisse=commandes.reduce((s,c)=>s+Number(c.total_final??c.total??0),0);
  const totalReel=commandes.reduce((s,c)=>s+Number(c.total||0),0);
  return <div className="space-y-4"><h2 className="text-xl font-bold text-white">Dashboard Aujourd'hui</h2><div className="grid grid-cols-2 gap-3"><StatCard icon={DollarSign} label="Encaissé vrai" value={`${totalEncaisse} DH`} color="text-green-400" bg="bg-green-950/30"/><StatCard icon={TrendingUp} label="Réel" value={`${totalReel} DH`} color="text-orange-400" bg="bg-orange-950/30"/><StatCard icon={ShoppingBag} label="Commandes" value={`${commandes.length}`} color="text-blue-400" bg="bg-blue-950/30"/><StatCard icon={TrendingUp} label="Perte OFFERT" value={`${totalReel-totalEncaisse} DH`} color="text-red-400" bg="bg-red-950/30"/></div></div>
}

function MenuTab(){
  const [menus,setMenus]=useState<Menu[]>([]); const [matieres,setMatieres]=useState<MatierePremiere[]>([]); const [recettes,setRecettes]=useState<Recette[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('Tous'); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Menu|null>(null); const [showForm,setShowForm]=useState(false);
  const load=useCallback(async()=>{ const [{data:m},{data:mp},{data:r},{data:cats}]=await Promise.all([supabase.from('menu').select('*').order('nom'), supabase.from('matiere_premiere').select('*').order('nom'), supabase.from('recette').select('*'), supabase.from('categories').select('*').order('ordre')]); setMenus(m||[]); setMatieres(mp||[]); setRecettes(r||[]); setCategories(cats||[]); setLoading(false); },[]);
  useEffect(()=>{load();},[load]);
  const filtered=menus.filter(m=>{ if(filter!=='Tous'&&m.categorie!==filter) return false; if(search&&!m.nom.toLowerCase().includes(search.toLowerCase())) return false; return true; });
  if(loading) return <LoadingSpinner/>;
  return <div className="space-y-4"><div className="flex justify-between"><h2 className="text-xl font-bold text-white">Menu - {filtered.length} plats</h2><button onClick={()=>{setEditing(null); setShowForm(true);}} className="bg-[#FF6B00] text-white px-4 py-2.5 rounded-xl flex items-center gap-2"><Plus className="w-4 h-4"/>Ajouter</button></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher..." className="w-full bg-[#1A1A1A] text-white rounded-xl py-2.5 pl-10 pr-4 border border-gray-800"/></div><div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setFilter('Tous')} className={`px-4 py-2 rounded-lg text-sm ${filter==='Tous'?'bg-[#FF6B00] text-white':'bg-[#1A1A1A] text-gray-400'}`}>Tous</button>{categories.map(c=><button key={c.id} onClick={()=>setFilter(c.nom)} className={`px-4 py-2 rounded-lg text-sm whitespace-nowrap ${filter===c.nom?'bg-[#FF6B00] text-white':'bg-[#1A1A1A] text-gray-400'}`}>{c.label}</button>)}</div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{filtered.map(m=><div key={m.id} className="bg-[#1A1A1A] rounded-2xl overflow-hidden border border-gray-800"><div className="h-32 bg-gray-900 relative">{m.image_url? <img src={m.image_url} className="w-full h-full object-cover"/> : <div className="flex h-full items-center justify-center"><ImageIcon className="w-8 h-8 text-gray-700"/></div>}<span className={`absolute top-2 right-2 px-2 py-1 rounded-lg text-xs ${m.disponible?'bg-green-600 text-white':'bg-red-600 text-white'}`}>{m.disponible?'Disponible':'Indisponible'}</span></div><div className="p-3"><div className="flex justify-between"><div><div className="text-white font-semibold text-sm">{m.nom}</div><div className="text-[#FF6B00] font-bold">{Number(m.prix).toFixed(0)} DH</div></div><div className="flex gap-1"><button onClick={()=>{setEditing(m); setShowForm(true);}} className="p-2 bg-gray-800 rounded-lg"><Edit3 className="w-4 h-4 text-gray-300"/></button><button onClick={async()=>{if(confirm('Supprimer?')){await supabase.from('recette').delete().eq('menu_id',m.id); await supabase.from('menu').delete().eq('id',m.id); load();}}} className="p-2 bg-red-950 rounded-lg"><Trash2 className="w-4 h-4 text-red-400"/></button></div></div></div></div>)}</div>{showForm && <MenuForm menu={editing} matieres={matieres} recettes={recettes} categories={categories} onClose={()=>{setShowForm(false); setEditing(null);}} onSaved={load}/>}</div>
}
function MenuForm({menu,matieres,recettes,categories,onClose,onSaved}:any){
  const [nom,setNom]=useState(menu?.nom||''); const [prix,setPrix]=useState(menu?String(menu.prix):''); const [categorie,setCategorie]=useState(menu?.categorie||categories[0]?.nom||'Plats'); const [image_url,setImageUrl]=useState(menu?.image_url||''); const [disponible,setDisponible]=useState(menu?.disponible??true); const [ingredients,setIngredients]=useState<any[]>(menu? recettes.filter((r:any)=>r.menu_id===menu.id).map((r:any)=>({matiere_id:r.matiere_id,qte:String(r.qte_necessaire)})):[]);
  const handleSave=async()=>{ const payload={nom,prix:parseFloat(prix),categorie,image_url,disponible}; let menuId=menu?.id; if(menu){ await supabase.from('menu').update(payload).eq('id',menu.id); await supabase.from('recette').delete().eq('menu_id',menu.id); } else { const {data}=await supabase.from('menu').insert(payload).select().single(); menuId=data?.id; } if(menuId&&ingredients.length){ const rows=ingredients.filter((i:any)=>i.matiere_id&&parseFloat(i.qte)>0).map((i:any)=>({menu_id:menuId,matiere_id:i.matiere_id,qte_necessaire:parseFloat(i.qte)})); if(rows.length) await supabase.from('recette').insert(rows); } onSaved(); onClose(); };
  return <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="bg-[#1A1A1A] rounded-2xl w-full max-w-lg border border-gray-800"><div className="flex justify-between p-5 border-b border-gray-800"><h3 className="text-white font-semibold">{menu?'Modifier':'Nouveau plat'}</h3><button onClick={onClose}><X className="w-5 h-5 text-gray-400"/></button></div><div className="p-5 space-y-3"><input value={nom} onChange={e=>setNom(e.target.value)} placeholder="Nom" className="w-full bg-[#0A0A0A] text-white rounded-xl py-2.5 px-3 border border-gray-700"/><div className="grid grid-cols-2 gap-2"><input type="number" value={prix} onChange={e=>setPrix(e.target.value)} placeholder="Prix" className="bg-[#0A0A0A] text-white rounded-xl py-2.5 px-3 border border-gray-700"/><select value={categorie} onChange={e=>setCategorie(e.target.value)} className="bg-[#0A0A0A] text-white rounded-xl py-2.5 px-3 border border-gray-700">{categories.map((c:any)=><option key={c.id} value={c.nom}>{c.label}</option>)}</select></div><input value={image_url} onChange={e=>setImageUrl(e.target.value)} placeholder="Image URL (optionnel)" className="w-full bg-[#0A0A0A] text-white rounded-xl py-2.5 px-3 border border-gray-700"/><label className="flex items-center gap-2 text-sm text-gray-400"><input type="checkbox" checked={disponible} onChange={e=>setDisponible(e.target.checked)}/> Disponible</label><div className="border-t border-gray-800 pt-3"><div className="flex justify-between mb-2"><span className="text-sm text-gray-400">Recette</span><button onClick={()=>setIngredients([...ingredients,{matiere_id:matieres[0]?.id||'',qte:'0.1'}])} className="text-[#FF6B00] text-sm">+ Ajouter</button></div>{ingredients.map((ing:any,idx:number)=><div key={idx} className="flex gap-2 mb-2"><select value={ing.matiere_id} onChange={e=>{const n=[...ingredients]; n[idx].matiere_id=e.target.value; setIngredients(n);}} className="flex-1 bg-[#0A0A0A] text-white rounded-lg py-2 px-2 border border-gray-700 text-sm">{matieres.map((mp:any)=><option key={mp.id} value={mp.id}>{mp.nom}</option>)}</select><input type="number" value={ing.qte} onChange={e=>{const n=[...ingredients]; n[idx].qte=e.target.value; setIngredients(n);}} className="w-20 bg-[#0A0A0A] text-white rounded-lg py-2 px-2 border border-gray-700 text-sm"/><button onClick={()=>setIngredients(ingredients.filter((_:any,i:number)=>i!==idx))} className="p-2 bg-red-950 rounded-lg"><Trash2 className="w-4 h-4 text-red-400"/></button></div>)}</div></div><div className="p-5 border-t border-gray-800 flex gap-2"><button onClick={onClose} className="flex-1 bg-gray-800 text-white py-3 rounded-xl">Annuler</button><button onClick={handleSave} className="flex-1 bg-[#FF6B00] text-white py-3 rounded-xl">Sauvegarder</button></div></div></div>
}

function StockTab(){ const [matieres,setMatieres]=useState<any[]>([]); useEffect(()=>{ supabase.from('matiere_premiere').select('*').order('nom').then(({data})=>setMatieres(data||[])); },[]); return <div className="space-y-3"><h2 className="text-xl font-bold text-white">Stock</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{matieres.map((mp:any)=>{ const isR=mp.quantite<=0; return <div key={mp.id} className={`bg-[#1A1A1A] rounded-2xl p-4 border ${isR?'border-red-600':'border-gray-800'}`}><div className="flex justify-between"><h4 className="text-white font-semibold">{mp.nom}</h4>{isR&&<span className="bg-red-600 text-white text-xs px-2 py-1 rounded-lg">RUPTURE</span>}</div><div className="text-2xl font-bold text-white mt-1">{Number(mp.quantite).toFixed(2)} <span className="text-sm text-gray-500">{mp.unite}</span></div><div className="text-xs text-gray-500">Seuil {mp.seuil_alerte}</div></div> })}</div></div> }
function CommandesTab(){ const [cmds,setCmds]=useState<any[]>([]); const [expanded,setExpanded]=useState<string|null>(null); useEffect(()=>{ const load=async()=>{ const {data}=await supabase.from('commandes').select('*').order('created_at',{ascending:false}).limit(100); if(data?.length){ const ids=data.map((c:any)=>c.id); const {data:items}=await supabase.from('commande_items').select('*').in('commande_id',ids); const m:any={}; (items||[]).forEach((it:any)=>{(m[it.commande_id]=m[it.commande_id]||[]).push(it);}); setCmds(data.map((c:any)=>({...c, items:m[c.id]||[]}))); } }; load(); },[]); return <div className="space-y-2"><h2 className="text-xl font-bold text-white">Commandes</h2>{cmds.map((c:any)=><div key={c.id} className="bg-[#1A1A1A] rounded-2xl border border-gray-800 overflow-hidden"><button onClick={()=>setExpanded(expanded===c.id?null:c.id)} className="w-full flex justify-between p-4"><span className="text-white text-sm">{c.serveur_nom} - {new Date(c.created_at).toLocaleTimeString('fr-FR')}</span><span className="flex gap-2"><StatusBadge statut={c.statut}/><span className="text-white font-bold">{Number(c.total_final??c.total).toFixed(0)} DH</span></span></button>{expanded===c.id&&<div className="p-4 border-t border-gray-800 space-y-1">{c.items?.map((it:any)=><div key={it.id} className="flex justify-between text-sm"><span className="text-gray-300">{it.qte}x {it.menu_nom}</span><span className="text-gray-400">{(it.qte*Number(it.prix)).toFixed(0)} DH</span></div>)}</div>}</div>)}</div> }
function MatiereTab(){ const [matieres,setMatieres]=useState<any[]>([]); const [editing,setEditing]=useState<any>(null); const [show,setShow]=useState(false); const load=useCallback(async()=>{ const {data}=await supabase.from('matiere_premiere').select('*').order('nom'); setMatieres(data||[]); },[]); useEffect(()=>{load();},[load]); return <div className="space-y-3"><div className="flex justify-between"><h2 className="text-xl font-bold text-white">Matière Première</h2><button onClick={()=>{setEditing(null); setShow(true);}} className="bg-[#FF6B00] text-white px-4 py-2 rounded-xl">+ Ajouter</button></div>{matieres.map((mp:any)=><div key={mp.id} className="bg-[#1A1A1A] rounded-2xl p-4 border border-gray-800 flex justify-between"><div><div className="text-white font-semibold">{mp.nom}</div><div className="text-gray-500 text-sm">{mp.quantite} {mp.unite}</div></div><div className="flex gap-2"><button onClick={()=>{setEditing(mp); setShow(true);}} className="p-2 bg-gray-800 rounded-lg"><Edit3 className="w-4 h-4 text-gray-300"/></button><button onClick={async()=>{if(confirm('Supprimer?')){await supabase.from('matiere_premiere').delete().eq('id',mp.id); load();}}} className="p-2 bg-red-950 rounded-lg"><Trash2 className="w-4 h-4 text-red-400"/></button></div></div>)}{show&&<MatiereForm matiere={editing} onClose={()=>{setShow(false); setEditing(null);}} onSaved={load}/>}</div> }
function MatiereForm({matiere,onClose,onSaved}:any){ const [nom,setNom]=useState(matiere?.nom||''); const [quantite,setQuantite]=useState(matiere?String(matiere.quantite):'0'); const [unite,setUnite]=useState(matiere?.unite||'kg'); const [seuil,setSeuil]=useState(matiere?String(matiere.seuil_alerte):'5'); const save=async()=>{ const p={nom,quantite:parseFloat(quantite)||0,unite,seuil_alerte:parseFloat(seuil)||0}; if(matiere) await supabase.from('matiere_premiere').update(p).eq('id',matiere.id); else await supabase.from('matiere_premiere').insert(p); onSaved(); onClose(); }; return <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="bg-[#1A1A1A] rounded-2xl w-full max-w-md border border-gray-800 p-5 space-y-3"><input value={nom} onChange={e=>setNom(e.target.value)} placeholder="Nom" className="w-full bg-[#0A0A0A] text-white rounded-xl py-2.5 px-3 border border-gray-700"/><div className="grid grid-cols-3 gap-2"><input type="number" value={quantite} onChange={e=>setQuantite(e.target.value)} className="bg-[#0A0A0A] text-white rounded-xl py-2 px-3 border border-gray-700"/><select value={unite} onChange={e=>setUnite(e.target.value)} className="bg-[#0A0A0A] text-white rounded-xl py-2 px-3 border border-gray-700"><option>kg</option><option>L</option><option>pcs</option><option>g</option></select><input type="number" value={seuil} onChange={e=>setSeuil(e.target.value)} className="bg-[#0A0A0A] text-white rounded-xl py-2 px-3 border border-gray-700"/></div><div className="flex gap-2"><button onClick={onClose} className="flex-1 bg-gray-800 text-white py-3 rounded-xl">Annuler</button><button onClick={save} className="flex-1 bg-[#FF6B00] text-white py-3 rounded-xl">Sauver</button></div></div></div> }
function CategoriesTab(){ const [cats,setCats]=useState<any[]>([]); const [menus,setMenus]=useState<any[]>([]); const [editing,setEditing]=useState<any>(null); const [show,setShow]=useState(false); const load=useCallback(async()=>{ const [{data:c},{data:m}]=await Promise.all([supabase.from('categories').select('*').order('ordre'), supabase.from('menu').select('*')]); setCats(c||[]); setMenus(m||[]); },[]); useEffect(()=>{load();},[load]); return <div className="space-y-3"><div className="flex justify-between"><h2 className="text-xl font-bold text-white">Catégories</h2><button onClick={()=>{setEditing(null); setShow(true);}} className="bg-[#FF6B00] text-white px-4 py-2 rounded-xl">+ Ajouter</button></div>{cats.map((cat:any)=><div key={cat.id} className="bg-[#1A1A1A] rounded-2xl p-4 border border-gray-800 flex justify-between"><div><div className="text-white font-semibold">{cat.label}</div><div className="text-gray-500 text-xs">{menus.filter((mm:any)=>mm.categorie===cat.nom).length} plats</div></div><div className="flex gap-2"><button onClick={()=>{setEditing(cat); setShow(true);}} className="p-2 bg-gray-800 rounded-lg"><Edit3 className="w-4 h-4 text-gray-300"/></button><button onClick={async()=>{if(confirm('Supprimer?')){await supabase.from('categories').delete().eq('id',cat.id); load();}}} className="p-2 bg-red-950 rounded-lg"><Trash2 className="w-4 h-4 text-red-400"/></button></div></div>)}{show&&<CategoryForm category={editing} onClose={()=>{setShow(false); setEditing(null);}} onSaved={load} />}</div> }
function CategoryForm({category,onClose,onSaved}:any){ const [label,setLabel]=useState(category?.label||''); const [nom,setNom]=useState(category?.nom||''); const save=async()=>{ const key=nom.toLowerCase().replace(/[^a-z0-9]/g,'_'); const p={nom:key,label,ordre:1}; if(category) await supabase.from('categories').update({label}).eq('id',category.id); else await supabase.from('categories').insert(p)
