// @ts-nocheck
import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/lib/supabase';
import { Edit3, Trash2, X, Plus } from 'lucide-react';

export default function Admin(){
  const [tab,setTab]=useState('rapports');
  return(
    <div className="min-h-screen bg-black text-white pb-20">
      <div className="flex gap-1 p-2 border-b border-zinc-800 sticky top-0 bg-black z-20 overflow-x-auto">
        {['menu','matiere','stock','categories','users','rapports'].map((t)=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 rounded-xl text-sm font-bold whitespace-nowrap ${tab===t?'bg-orange-600':'bg-zinc-800'}`}>{t.toUpperCase()}</button>)}
      </div>
      <div className="p-4 max-w-5xl mx-auto">
        {tab==='menu'&&<MenuTab/>}{tab==='matiere'&&<MatiereTab/>}{tab==='stock'&&<StockTab/>}{tab==='categories'&&<CategoriesTab/>}{tab==='users'&&<UsersTab/>}{tab==='rapports'&&<RapportsTab/>}
      </div>
    </div>
  );
}

function MenuTab(){
  const [menus,setMenus]=useState([]);const [cats,setCats]=useState([]);const [mats,setMats]=useState([]);const [rec,setRec]=useState([]);const [show,setShow]=useState(false);const [edit,setEdit]=useState(null);
  const load=useCallback(async()=>{const a=await supabase.from('menu').select('*').order('nom');const b=await supabase.from('categories').select('*').order('ordre');const c=await supabase.from('matiere_premiere').select('*').order('nom');const d=await supabase.from('recette').select('*');setMenus(a.data||[]);setCats(b.data||[]);setMats(c.data||[]);setRec(d.data||[]);},[]);
  useEffect(()=>{load();},[load]);
  return <div><div className="flex justify-between mb-3"><h2 className="font-bold">Menu {menus.length}</h2><button onClick={()=>{setEdit(null);setShow(true);}} className="bg-orange-600 px-4 py-2 rounded-xl font-bold">+ Plat</button></div><div className="grid md:grid-cols-2 gap-3">{menus.map((m)=>{const ings=rec.filter((r)=>r.menu_id===m.id);return <div key={m.id} className="bg-zinc-900 rounded-xl border border-zinc-800 overflow-hidden"><div className="h-40 bg-zinc-800">{m.image_url?<img src={m.image_url} className="w-full h-full object-cover"/>:<div className="h-full flex items-center justify-center text-xs text-zinc-500">Sans photo</div>}</div><div className="p-3"><div className="flex justify-between"><div><div className="font-bold">{m.nom} - {m.prix} DH</div></div><div className="flex gap-1"><button onClick={()=>{setEdit(m);setShow(true);}} className="p-2 bg-zinc-800 rounded-lg"><Edit3 className="w-4 h-4"/></button><button onClick={async()=>{if(confirm('Supprimer?')){await supabase.from('menu').delete().eq('id',m.id);load();}}} className="p-2 bg-red-900 rounded-lg"><Trash2 className="w-4 h-4"/></button></div></div></div></div>})}</div>{show&&<MenuForm menu={edit} categories={cats} matieres={mats} recs={rec.filter((r)=>r.menu_id===edit?.id)} onClose={()=>{setShow(false);setEdit(null);}} onSaved={load}/>}</div>
}
function MenuForm({menu,categories,matieres,recs,onClose,onSaved}){
  const [nom,setNom]=useState(menu?.nom||'');const [prix,setPrix]=useState(menu?String(menu.prix):'');const [cat,setCat]=useState(menu?.categorie||categories[0]?.nom||'');const [img,setImg]=useState(menu?.image_url||'');const [ings,setIngs]=useState(recs||[]);const [sel,setSel]=useState('');const [qte,setQte]=useState('150');const [unite,setUnite]=useState('g');
  useEffect(()=>{ if(matieres.length &&!sel){ const first=matieres.find((m)=>!ings.some((i)=>i.matiere_id===m.id))||matieres[0]; setSel(first?.id||''); setUnite(first?.unite||'g'); } },[matieres]);
  const addIng=()=>{if(!sel) return; const q=parseFloat(qte); if(!q) return; const mat=matieres.find((x)=>x.id===sel); if(!mat) return; const newIngs=[...ings,{matiere_id:sel, qte_necessaire:q, _nom:mat.nom, unite}]; setIngs(newIngs); const next=matieres.find((m)=>!newIngs.some((i)=>i.matiere_id===m.id)); if(next){ setSel(next.id); setUnite(next.unite||'g'); } setQte('150');};
  const save=async()=>{if(!nom||!prix) return alert('Nom + Prix'); const p={nom,prix:parseFloat(prix)||0,categorie:cat,image_url:img,disponible:true}; let id=menu?.id; if(menu){await supabase.from('menu').update(p).eq('id',menu.id);}else{const {data}=await supabase.from('menu').insert(p).select().single(); id=data?.id;} if(id){await supabase.from('recette').delete().eq('menu_id',id); if(ings.length){await supabase.from('recette').insert(ings.map((x)=>({menu_id:id, matiere_id:x.matiere_id, qte_necessaire:x.qte_necessaire, unite:x.unite})));}} onSaved(); onClose();};
  return <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4"><div className="bg-zinc-900 rounded-2xl w-full max-w-lg border border-zinc-800"><div className="p-4 flex justify-between border-b border-zinc-800"><h3 className="font-bold">Plat - {ings.length} ing</h3><button onClick={onClose}><X className="w-5 h-5"/></button></div><div className="p-4 space-y-3 max-h-[75vh] overflow-auto"><input value={nom} onChange={e=>setNom(e.target.value)} placeholder="Nom" className="w-full bg-black p-3 rounded-xl border border-zinc-700"/><div className="flex gap-2"><input value={prix} onChange={e=>setPrix(e.target.value)} type="number" placeholder="Prix" className="flex-1 bg-black p-3 rounded-xl border border-zinc-700"/><select value={cat} onChange={e=>setCat(e.target.value)} className="flex-1 bg-black p-3 rounded-xl border border-zinc-700">{categories.map((c)=><option key={c.id} value={c.nom}>{c.label}</option>)}</select></div><div className="bg-black border-2 border-orange-500/30 rounded-xl p-3"><select value={sel} onChange={e=>{setSel(e.target.value);}} className="w-full bg-zinc-800 p-3.5 rounded-xl border border-zinc-700 mb-2 font-bold">{matieres.map((m)=>{const used=ings.some((i)=>i.matiere_id===m.id); return <option key={m.id} value={m.id}>{used?'✅ ':''}{m.nom}</option>})}</select><div className="flex gap-2 mb-2"><input value={qte} onChange={e=>setQte(e.target.value)} type="number" className="flex-1 bg-zinc-800 p-3.5 rounded-xl border border-zinc-700 text-center font-black text-lg"/><select value={unite} onChange={e=>setUnite(e.target.value)} className="w-20 bg-zinc-800 p-3.5 rounded-xl border border-zinc-700 font-bold"><option>g</option><option>kg</option><option>ml</option><option>L</option><option>pcs</option></select></div><button onClick={addIng} className="w-full bg-orange-600 py-4 rounded-xl font-black">+ Ajouter</button><div className="mt-3 space-y-1">{ings.map((ig,i)=><div key={i} className="flex justify-between bg-zinc-800 rounded-xl p-2.5 text-sm border border-zinc-700"><span className="font-bold">{i+1}. {ig.qte_necessaire} {ig.unite} - {ig._nom}</span><button onClick={()=>setIngs(ings.filter((_,idx)=>idx!==i))} className="text-red-400 font-black">X</button></div>)}</div></div></div><div className="p-4 border-t border-zinc-800 flex gap-2"><button onClick={onClose} className="flex-1 bg-zinc-800 py-3 rounded-xl">Annuler</button><button onClick={save} className="flex-1 bg-orange-600 py-3 rounded-xl font-bold">Sauver {ings.length}</button></div></div></div>
}
function UsersTab(){const [users,setUsers]=useState([]);const [show,setShow]=useState(false);const [edit,setEdit]=useState(null);const load=useCallback(async()=>{const {data}=await supabase.from('utilisateurs').select('*').order('created_at',{ascending:false});setUsers(data||[]);},[]);useEffect(()=>{load();},[load]);return <div><div className="flex justify-between mb-3"><h2 className="font-bold">Users {users.length}</h2><button onClick={()=>{setEdit(null);setShow(true);}} className="bg-orange-600 px-4 py-2 rounded-xl font-bold">+ User</button></div>{users.map((u)=><div key={u.id} className="bg-zinc-900 p-4 rounded-xl border border-zinc-800 flex justify-between mb-2"><div><div className="font-bold">{u.nom} <span className="text-xs bg-zinc-800 px-2 py-1 rounded-lg ml-2">{u.role}</span></div><div className="text-xs text-zinc-500">ID: {u.identifiant}</div></div><div className="flex gap-1"><button onClick={()=>{setEdit(u);setShow(true);}} className="p-2.5 bg-zinc-800 rounded-xl"><Edit3 className="w-4 h-4"/></button><button onClick={async()=>{if(confirm('Supprimer?')){await supabase.from('utilisateurs').delete().eq('id',u.id);load();}}} className="p-2.5 bg-red-
